### ISSUE TITLE
No constructor with String param

### ISSUE THREAD

**Issue by karanatwal** [iammannan/EasyNotifyLibProject#3]
`EasyNotify easyNotify = new EasyNotify("YOUR_APP_API_KEY");`
No such constructor in source code.
Neither below these methods -
```
easyNotify.setSendBy(EasyNotify.TOPIC);
   or
 easyNotify.setSendBy(EasyNotify.TOKEN);
```
**Please check source code looks like you have committed wrong code.**

**Comment by iammannan** [comment]
Fixed! Check v1.2
