### ISSUE TITLE
Constructor and sendByToken not implemented in lastest version 1.1

### ISSUE THREAD

**Issue by riyanirawan007** [iammannan/EasyNotifyLibProject#4]
Can you check your code, there's no constructor and sendbyToken feature ?. Thanks, keep this library going on. below some parameters that we can set

`  
    public void setNtitle(String ntitle) {
        this.ntitle = ntitle;
    }

    public void setNbody(String nbody) {
        this.nbody = nbody;
    }

    public void setNclick_action(String nclick_action) {
        this.nclick_action = nclick_action;
    }

    public void setNtopic(String ntopic) {
        this.ntopic = ntopic;
    }

    public void setAPI_KEY(String API_KEY) {
        this.API_KEY = API_KEY;
    }

    public void setNsound(String nsound) {
        this.nsound = nsound;
    }

    public void setEasyNotifyListener(EasyNotifyListener listener)
    {
        this.listener=listener;
    }`

**Comment by iammannan** [comment]
Sorry, codes are modified, check v1.2
